language: cpp

matrix:
  include:
      - os: linux
        addons:
          apt:
            sources:
              - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
              - g++-8
      env:
        - MATRIX_EVAL="cc=gcc-8 CXX=g++-8"

before_install:
  - sudo apt-get install -y mesa-utils libglew-dev glew-utils libglfw3-dev
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_BUILD_TYPE=Release
  - make -j
  - cmake -DCMAKE_BUILD_TYPE=Debug
  - make -j
