language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y g++-8 mesa-utils libglew-dev glew-utils libglfw3-dev

script:
  - cmake -DCMAKE_BUILD_TYPE=Release
  - make -j
  - cmake -DCMAKE_BUILD_TYPE=Debug
  - make -j
