language: cpp
compiler: gcc
dist: xenial

before_install:
  # Adding the test repository of ubuntu
  - sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
  - sudo apt-get update -qq

  # Adding LLVM repository
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
  - sudo apt-get update -qq
  - sudo apt-get install -y clang-7.0

  # Installing Essential Libraries
install:
  # GNU Compiler
  - sudo apt-get install -y g++-8 

  # OpenGL
  - sudo apt-get install -y mesa-utils libglew-dev glew-utils libglu1-mesa-dev

  # X11
  - sudo apt-get install -y libx11-dev xorg-dev # X11

  # GLFW3
  - git clone https://github.com/glfw/glfw.git GLFW3
  - cd GLFW3 && mkdir build && cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - make -j
  - sudo make install
  - cd .. # go back to glfw3 folder
  - cd .. # go back to project

script:
  # Compiling Debug and Release Mode.
  # GCC
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8
  - make -j
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-8
  - make -j
  # CLANG
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++-7
  - make -j
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-7
  - make -j
